# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  imageName: 'pipelines-javascript-docker'
  dockerHub: 'danwin-dockerhub'
  tag: 'test'

steps:
- task: Docker@2
  displayName: Docker build and push image
  inputs:
    command: buildAndPush
    containerRegistry: $(dockerHub)
    Dockerfile: app/Dockerfile
    repository: $(imageName)
    tags: $(tag)
